### PR TITLE
Lesson 02

### PR DESCRIPTION
**Pull request by ovdiyuk**
The home task is done and ready for review.

### CODE REVIEW

**Comment by ovdiyuk** [comment]
Sorry, it looks like Labeling function is disabled for me. Right?
I wished to add "READY"

**Comment by OlegH-ua** [comment]
The same thing. I can't find possibility to set label and assign reviewers either

**Comment by ovdiyuk** [comment]
Please see https://github.com/Kernel-GL-HRK/gl-kernel-training-2018/pull/34 new PR

**Comment by ovdiyuk** [comment]
not actual anymore. new PR https://github.com/Kernel-GL-HRK/gl-kernel-training-2018/pull/34 had been reviewed

**Pull request closed without merging**
