### PR TITLE
10-ConcurrencyAndSynchronization: implement homework

### PR DESCRIPTION
**Pull request by nikishyn**
Please review task. if everything is good, make a pull

### CODE REVIEW

**Review by IevgenMaliarenko — COMMENTED** [review]
Looks like that first commit is not an initial commit of development process with non-informative commit-message

**Comment by IevgenMaliarenko** [comment]
Try to keep changes like a 

> Replace spinlock with real time mutex.
> Fix checkpatch error

within separate commits

**Comment by IevgenMaliarenko** [comment]
Please provide conclusions regarding spin lock and rt-mutex using. Thanks.

**Comment by nikishyn** [comment]
> Please provide conclusions regarding spin lock and rt-mutex using. Thanks.

When a thread tries to lock a mutex and it does not succeed, because the mutex is already locked, it will go to sleep, immediately allowing another thread to run. It will continue to sleep until being woken up, which will be the case once the mutex is being unlocked by whatever thread was holding the lock before. When a thread tries to lock a spinlock and it does not succeed, it will continuously re-try locking it, until it finally succeeds; thus it will not allow another thread to take its place. 

**Based on this, it makes no sense to use spinlock on single-core systems.**

**Pull request merged**
